# app/parts_data.py
PARTS = [
    # Belt System
    "Belt",
    "Drive Belt",
    "Timing Belt",
    "V-Belt",
    "Idler Roller",
    "Drive Pulley",
    "Tension Pulley",
    
    # Motor and Drive
    "Motor",
    "AC Motor",
    "DC Motor",
    "Servo Motor",
    "Stepper Motor",
    "Drive",
    "VFD",
    "Gearbox",
    "Coupling",
    "Shaft",
    
    # Sensors and Electronics
    "Sensor",
    "Proximity Sensor",
    "Photo Eye",
    "Encoder",
    "Position Sensor",
    "Pressure Sensor",
    "Temperature Sensor",
    "Flow Sensor",
    "Level Sensor",
    "Switch",
    "Limit Switch",
    "Relay",
    "Contactor",
    "Fuse",
    "Circuit Breaker",
    "Circuit Board",
    "PLC Module",
    "HMI",
    "Display",
    "Button",
    "Indicator Light",
    
    # Pneumatic/Hydraulic
    "Valve",
    "Solenoid Valve",
    "Relief Valve",
    "Check Valve",
    "Cylinder",
    "Actuator",
    "Filter",
    "Air Filter",
    "Hydraulic Filter",
    "Pump",
    "Compressor",
    "Accumulator",
    "Hose",
    "Fitting",
    "Quick Connect",
    
    # Mechanical Components
    "Bearing",
    "Ball Bearing",
    "Roller Bearing",
    "Pillow Block",
    "Bushing",
    "Gasket",
    "O-Ring",
    "Seal",
    "Spring",
    "Compression Spring",
    "Extension Spring",
    "Torsion Spring",
    "Lever",
    "Cam",
    "Gear",
    "Sprocket",
    "Chain",
    "Pulley",
    "Roller",
    "Guide Rail",
    "Linear Bearing",
    
    # Fasteners
    "Bolt",
    "Screw",
    "Cap Screw",
    "Set Screw",
    "Nut",
    "Lock Nut",
    "Washer",
    "Lock Washer",
    "Pin",
    "Cotter Pin",
    "Roll Pin",
    "Rivet",
    "Clamp",
    "U-Bolt",
    
    # Electrical
    "Cable",
    "Wire",
    "Conduit",
    "Connector",
    "Terminal",
    "Junction Box",
    "Control Panel",
    "Transformer",
    "Capacitor",
    "Resistor",
    "Inductor",
    
    # Structural/Housing
    "Cover",
    "Guard",
    "Shield",
    "Housing",
    "Frame",
    "Panel",
    "Door",
    "Handle",
    "Latch",
    "Hinge",
    "Bracket",
    "Mount",
    "Plate",
    "Strip",
    "Bar",
    "Angle",
    "Channel",
    
    # Miscellaneous
    "Key",
    "Lock",
    "Lubricant",
    "Grease",
    "Oil",
    "Coolant",
    "Adhesive",
    "Tape",
    "Label",
    "Tag"
]
